<a href="https://colab.research.google.com/github/hina81/Prog2_11th/blob/main/work2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import auth
from wordcloud import WordCloud
import gspread
from google.auth import default
import pandas as pd
import numpy as np
import datetime
import csv

In [15]:
#csvファイル名を変更してください
df = pd.read_csv('希望シフト【期間を記入】  .csv')

In [21]:
#google formからの情報をNumPy配列に変換します
name = []
for na in df['お名前']:
  name.append(na)
#print(name)

mon = []
tue = []
wed = []
thu = []
fri = []
sat = []
sun = []

for sft in df['希望シフト']:
  if '月' in sft:
    mon.append(1)
  else:
    mon.append(0)

  if '火' in sft:
    tue.append(1)
  else:
    tue.append(0)

  if '水' in sft:
    wed.append(1)
  else:
    wed.append(0)

  if '木' in sft:
    thu.append(1)
  else:
    thu.append(0)

  if '金' in sft:
    fri.append(1)
  else:
    fri.append(0)

  if '土' in sft:
    sat.append(1)
  else:
    sat.append(0)


  if '日' in sft:
    sun.append(1)
  else:
    sun.append(0)

data = np.array([mon, tue, wed, thu, fri, sat, sun])
data_T = data.T

In [25]:
#行が人、列が曜日
print(data_T)

[[1 1 0 1 0 0 1]
 [0 1 1 0 0 0 0]
 [1 1 1 0 0 0 0]
 [0 1 1 0 1 1 0]
 [1 0 0 0 0 0 1]
 [0 1 0 0 1 0 0]
 [1 1 1 0 0 0 1]
 [0 0 0 0 1 1 1]
 [0 0 1 1 0 0 0]
 [1 0 0 1 0 1 0]
 [0 0 0 0 0 1 1]]


In [31]:
#日ごとの希望者数
kibou = np.sum(data_T, axis=0)
print(kibou)
#一週間の希望勤務時間
zikan_sum = np.sum(data_T,axis=1)
print(zikan_sum)

[5 6 5 3 3 4 5]
[4 2 3 4 2 2 4 3 2 3 2]


In [32]:
for i,day in enumerate(kibou, 0):
  if day > 4:
    np.put(data_T[np.argmax(zikan_sum),i],data_T, 0)

print(data_T)

IndexError: index 1 is out of bounds for axis 0 with size 1